backend:
  name: github
  repo: yipalan/yipalan.github.io # Replace with your actual repo name
  branch: main

media_folder: "images" # Where your photos will be saved
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Language", name: "lang", widget: "select", options: ["en", "ja", "es"] }
      - { label: "Body", name: "body", widget: "markdown" }
